# roles/nfs/tasks/main.yml
---
- name: "Include {{ ansible_distribution }} variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: "Include {{ ansible_distribution }} tasks"
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: Ensure directories exists
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default('openio') }}"
    group: "{{ item.group | default('openio') }}"
    mode: "{{ item.mode | default(0755) }}"
  with_items:
    - path: "/etc/gridinit.d/{{ openio_nfs_namespace }}"
    - path: "{{ openio_nfs_sysconfig_dir }}/{{ openio_nfs_servicename }}"
    #- path: "{{ openio_nfs_volume }}"
    #- path: "{{ openio_nfs_pid_directory }}"
    - path: "/var/log/oio/sds/{{ openio_nfs_namespace }}/{{ openio_nfs_servicename }}"
      owner: "{{ syslog_user }}"
      mode: "0750"
  tags: install

- name: Generate configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: openio
    group: openio
    mode: 0644
  with_items:
    - src: "nfs.conf.j2"
      dest: "{{ openio_nfs_sysconfig_dir }}/\
        {{ openio_nfs_servicename }}/{{ openio_nfs_servicename }}.conf"
    - src: "gridinit_nfs.conf.j2"
      dest: "{{ openio_nfs_gridinit_dir }}/{{ openio_nfs_gridinit_file_prefix }}\
        {{ openio_nfs_servicename }}.conf"
  register: _nfs_conf
  tags: configure

- name: restart nfs
  shell: |
    gridinit_cmd reload
    gridinit_cmd restart  {{openio_nfs_namespace}}-{{openio_nfs_servicename}}
  when:
    - _nfs_conf.changed
    - not openio_nfs_provision_only
  tags: configure
...
