---
- name: Install packages
  package:
    name: "{{ pkg }}"
    state: present
  with_items: "{{ openio_nfs_packages }}"
  loop_control:
    loop_var: pkg
  ignore_errors: "{{ ansible_check_mode }}"
  register: install_packages
  until: install_packages is success
  retries: 5
  delay: 2

- name: Ensure RPC bind is running
  service:
    name: rpcbind
    state: started
    enabled: true
...
